layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: espositofederico44
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: https://espositofederico44.com
  youtube: espositofederico44

topics:
  - name: Golang
    web_url: https://golang.org/
    image_url: /assets/img/golang.jpg

  - name: Python
    web_url: https://www.python.org/
    image_url: /assets/img/python.jpg

  - name: PostgreSQL
    web_url: https://www.postgresql.org/
    image_url: /assets/img/postgresql.jpg
